import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans bg-white">
        <div className="laptop:hidden flex flex-col justify-center items-center">
          <p className="text-primary text-lg mt-24">View On Larger Browser</p>
          <p className="text-sm">Designed for Desktop Only</p>
        </div>
        <div className="hidden laptop:flex absolute w-full flex-col">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
